### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by salahhadjar** [Xewdy444/CF-Clearance-Scraper#10]
i have problem on  adding this solver  in my bot would you please help me on it because am facing turnstile hcaptcha in my target website

**Comment by Xewdy444** [comment]
Could you explain a little more on what the problem is? The scraper should automatically reload the page if a turnstile captcha is given.

**Comment by salahhadjar** [comment]
Could you please message me on email test.live05@gmail.com or telegram @is_c0d3rz

**Comment by Xewdy444** [comment]
You con contact me on Discord @ Xewdy#7378
