### ISSUE TITLE
Failed to retrieve cf_clearance cookie.

### ISSUE THREAD

**Issue by JulesLePrince** [Xewdy444/CF-Clearance-Scraper#11]
I get this error message when trying to run the main.py file. I do have the playwright 1.28 version:
```
$ python3.9 main.py -u https://nowsecure.nl -f cookies.json -v
[23:27:32] [INFO] Launching headless browser...
[23:27:35] [INFO] Going to https://nowsecure.nl...
[23:27:35] [INFO] Solving cloudflare challenge [Managed]...
[23:28:18] [ERROR] Failed to retrieve cf_clearance cookie.
```

**Comment by Xewdy444** [comment]
For the time being, try using a different python version. I'll try to get a fix out soon.

**Comment by JulesLePrince** [comment]
Cool! which version of python would you recommend me to use? (I currently use 3.9)

**Comment by Xewdy444** [comment]
I would recommend 3.8 or 3.11

**Comment by Xewdy444** [comment]
I'm going to close this issue because I'm not really sure why this it is occurring.
