### ISSUE TITLE
Failed to get cookies after using the proxy

### ISSUE THREAD

**Issue by lqdm** [Xewdy444/CF-Clearance-Scraper#12]
[14:22:08] [INFO] Launching headless browser...
{'server': 'http//:xx.xx.xx.xx:8000:xx:xx'}
[14:22:10] [INFO] Going to https://nowsecure.nl...
[14:22:10] [ERROR] The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 310.)
=========================== logs ===========================
navigating to "https://nowsecure.nl/", waiting until "load"
============================================================

**Comment by Xewdy444** [comment]
If your proxy server requires authentication, then you should format the proxy URL like this:

`protocol://username:password@host:port`

**Comment by lqdm** [comment]
Thank you very much

**Comment by lqdm** [comment]
Man, I tried, but I can't. I suspect it's my agency

[10:53:45] [INFO] Going to https://nowsecure.nl...
[10:53:49] [ERROR] net::ERR_PROXY_CONNECTION_FAILED at https://nowsecure.nl/
=========================== logs ===========================
navigating to "https://nowsecure.nl/", waiting until "load"
============================================================

But you can give me your collection address (USDT). I'd like to contribute to the project (buy you a coffee hahh).

**Comment by Xewdy444** [comment]
Yea, if the proxy URL is formatted correctly, then it is probably just a connection issue. Another thing to note is that the use of a Chrome user agent can cause difficulties with solving Cloudflare managed challenges. However, if it is a JavaScript challenge, there should not be a problem.

If you'd like to support me, here is my USDT address:
`G55msLeHLgX6ET1kJJCYJkSFPoiBGYb7dr9UVo4QvUN8`

Any donation is very much appreciated!

**Comment by lqdm** [comment]
emmmm  Do you have the eth network payment address? This is all I have

**Comment by Xewdy444** [comment]
My ethereum address is `0xc6595803F7Dd4aF63B383b57a89c98A1F3B246B0`
