### ISSUE TITLE
error

### ISSUE THREAD

**Issue by perfect01** [Xewdy444/CF-Clearance-Scraper#13]
10:10:21] [INFO] Solving Cloudflare challenge [Managed]...
[10:17:36] [ERROR] Timeout 15000ms exceeded.
=========================== logs ===========================
  checking visibility of locator("#challenge-spinner")
============================================================
[10:17:36] [ERROR] Failed to retrieve the Cloudflare clearance cookie.

useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

how fix this?

**Comment by Xewdy444** [comment]
Try changing the user agent to something other than Chrome. Cloudflare has a hard time validating the browser if a Chrome user agent is used.

**Comment by perfect01** [comment]
> Try changing the user agent to something other than Chrome. Cloudflare has a hard time validating the browser if a Chrome user agent is used.

Work thanks
