### ISSUE TITLE
[ERROR] Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by ZzZombo** [Xewdy444/CF-Clearance-Scraper#15]
But isn't it the normal behavior for CF checks? At least for me it reloads the page whether it lets me through or not even if I'm visiting CF-protected pages normally outside this tool. So it's expected that after passing the checks the page could be navigated away, because as far as I know, CF passes some data through the query string appended to the current URL.

**Comment by Xewdy444** [comment]
Yes, you are correct, this is normal behavior for Cloudflare challenges. This error doesn't have any impact on the functionality of the program, so you can safely ignore it.
