### ISSUE TITLE
Not click verify button

### ISSUE THREAD

**Issue by jakkapong1129** [Xewdy444/CF-Clearance-Scraper#17]
![image](https://github.com/Xewdy444/CF-Clearance-Scraper/assets/60910772/103d4672-7f11-402d-9bd6-533edc0e32ae)

**Comment by Xewdy444** [comment]
This program currently will not be able to solve turnstile challenges due to an issue with Playwright. For more information, see https://github.com/microsoft/playwright/issues/21780. As a temporary solution, pass the -d flag and solve the challenge manually.
