### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by TestDeTuring** [Xewdy444/CF-Clearance-Scraper#20]
Is your feature request related to a problem? Please describe.
Hello, i need a cf_clearance for each proxy i send, but they don't contain the challenge, hence i can't get the cookies to keep my program working

Describe the solution you'd like
A mode maybe, where if active, every request will have a challenge

Describe alternatives you've considered
I can do this using a network sniffer, once cloudflare sees it's capturing info, they always throw the challenge, but not in proxies, since the sniffer is not active there, i was wondering if the program could disguise as a sniffer so it throws the challenge

Additional context
.

**Comment by Xewdy444** [comment]
Try using the `--disable-http2` and/or `--disable-http3` options. You can also try changing the user agent to match an older version of Firefox.

**Comment by TestDeTuring** [comment]
> Try using the `--disable-http2` and/or `--disable-http3` options. You can also try changing the user agent to match an older version of Firefox.

I've already tried with both options, i haven't tried an older UA, do you happen to know one that usually throws challenges?

**Comment by Xewdy444** [comment]
It mainly depends on the website's Cloudflare configuration. If you don't mind, could you tell me the website that you are having issues with?

**Comment by TestDeTuring** [comment]
Sure, the site is NordVPN, CF captcha appears once you try to go to the login page

**Comment by Xewdy444** [comment]
You were correct about Cloudflare detecting the network sniffer, as Cloudflare uses an [HTTPS interception detector](https://blog.cloudflare.com/monsters-in-the-middleboxes/) to detect things like this and issue challenges accordingly. Unfortunately, there is no way to disguise the browser as a network sniffer to my knowledge. 

I was able to make the website issue a challenge by specifying my Burpe Suite proxy as the proxy for the browser via `-p http://localhost:8080` and setting the user agent to the one used by Burpe Suite via `-ua "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.50 Safari/537.36"`, however Cloudflare did not let the browser pass the challenge as this browser has a hard time passing challenges while using Chrome user agents as specified in https://github.com/Xewdy444/CF-Clearance-Scraper/issues/7.

**Comment by TestDeTuring** [comment]
> You were correct about Cloudflare detecting the network sniffer, as Cloudflare uses an [HTTPS interception detector](https://blog.cloudflare.com/monsters-in-the-middleboxes/) to detect things like this and issue challenges accordingly. Unfortunately, there is no way to disguise the browser as a network sniffer to my knowledge.
> 
> I was able to make the website issue a challenge by specifying my Burpe Suite proxy as the proxy for the browser via `-p http://localhost:8080` and setting the user agent to the one used by Burpe Suite via `-ua "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.50 Safari/537.36"`, however Cloudflare did not let the browser pass the challenge as this browser has a hard time passing challenges while using Chrome user agents as specified in #7.

Got it, isn't there a workaround this?, launching the first browser with a https interceptor in it could work?

**Comment by Xewdy444** [comment]
I'll look into it.

**Comment by TestDeTuring** [comment]
Thank you, please do let me know

**Comment by TestDeTuring** [comment]
I've found that changin the UA to something with "Bot" ej "Botmasters" Will always throw a solvable challenge.

**Comment by TestDeTuring** [comment]
Sorry for reopening this, i was thinking and, wouldn't installing burp and launching it with the browser work?
