### ISSUE TITLE
[Feature request] Show source data

### ISSUE THREAD

**Issue by TestDeTuring** [Xewdy444/CF-Clearance-Scraper#21]
Hello, sorry for making all these requests, i'd love to help you, you can contact me if you need anything
would it be possible to add an option to show the whole source data from the page?

**Comment by TestDeTuring** [comment]
Sorry, more specifically, i need to know md, sh, and aw they are sent in the post data, but i don't know how to get them.

**Comment by Xewdy444** [comment]
This seems a little out of scope for this project as it is only meant to retrieve Cloudflare clearance cookies and not any other information about the challenge.
