### ISSUE TITLE
No Cloudflare challenge detected.

### ISSUE THREAD

**Issue by hamed-jamali-software** [Xewdy444/CF-Clearance-Scraper#24]
It says wrong if it exists

https://ir-appointment.visametric.com/ir 

 [ERROR] No Cloudflare challenge detected.

**Comment by sean-tan** [comment]
yea.. i  noticed this just happening a few days ago....

**Comment by Xewdy444** [comment]
Thanks for letting me know about this issue. It has been fixed in the latest commit.

**Comment by hamed-jamali-software** [comment]
headless=True
When this is active it is very slow or sometimes it doesn't work at all, it takes more than 120 seconds

**Comment by Xewdy444** [comment]
Are you receiving a turnstile challenge? If so, you will need to solve it manually by passing the `-d` flag for the time being.

**Comment by hamed-jamali-software** [comment]
verify_button = self.page.get_by_role("button", name=verify_button_pattern)

Whether in debug or normal mode, the problem is this line of code

I replaced with below code but still we have error

self.page.locator("//*[@id='challenge-stage']/div/label/input")


problem
this is not Automatic   find checkbox and click

**Comment by Xewdy444** [comment]
https://github.com/microsoft/playwright/issues/21780

**Comment by joseRodenasMinderest** [comment]
Hello @Xewdy444, congrats for your work. Do you know if there is a way to configure Firefox to enable the interactions with the frame? Via about:config properties or so? Thx in advance

**Comment by Xewdy444** [comment]
I don't believe there is any workaround as this is just a bug with Playwright.

**Comment by sean-tan** [comment]
hi,

Your fix worked.... but now its stuck at
Solving Cloudflare challenge [Managed]...


any idea whats wrong?

**Comment by Xewdy444** [comment]
> Are you receiving a turnstile challenge? If so, you will need to solve it manually by passing the `-d` flag for the time being.

@sean-tan
