### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 9de** [Xewdy444/CF-Clearance-Scraper#26]

**Comment by Xewdy444** [comment]
Could you please explain more about the issue you're experiencing

**Comment by rotorotoroto** [comment]
> Could you please explain more about the issue you're experiencing

All responses are "[ERROR] No Cloudflare challenge detected."

**Comment by Xewdy444** [comment]
This issue was recently fixed, therefore you can just clone the repository again to fix this issue.

**Comment by rotorotoroto** [comment]
Ok, just cloned the latest repository. Now I get:

[ERROR] Failed to retrieve the Cloudflare clearance cookie.

Tried 3 sites that give cloudflare challenges on first visit.

**Comment by Xewdy444** [comment]
*This program currently will not be able to solve turnstile challenges due to an issue with Playwright. For more information, see https://github.com/microsoft/playwright/issues/21780. As a temporary solution, pass the -d flag and solve the challenge manually.*

**Comment by rotorotoroto** [comment]
> _This program currently will not be able to solve turnstile challenges due to an issue with Playwright. For more information, see [microsoft/playwright#21780](https://github.com/microsoft/playwright/issues/21780). As a temporary solution, pass the -d flag and solve the challenge manually._

I passed it with the -d flag and it didn't lead me to a turnstile challenge but just to a click to "Verifiy you are human" type verification. After clicking manually on the newly opened browser, the CLI responded with the cookie.

Running the command without -d right after failed again.

**Comment by Xewdy444** [comment]
Should be fixed in the latest commit.

**Comment by rotorotoroto** [comment]
> Should be fixed in the latest commit.

Cloned the latest commit and ran "python main.py -v https://nowsecure.nl":

[22:01:55] [INFO] Launching headless browser...
[22:01:56] [INFO] Going to https://nowsecure.nl...
[22:01:57] [INFO] Solving Cloudflare challenge [Managed]...
[22:02:27] [ERROR] Failed to retrieve the Cloudflare clearance cookie.

**Comment by Xewdy444** [comment]
> *This program currently will not be able to solve turnstile challenges due to an issue with Playwright. For more information, see https://github.com/microsoft/playwright/issues/21780. As a temporary solution, pass the -d flag and solve the challenge manually.*

^

**Comment by rotorotoroto** [comment]
> > _This program currently will not be able to solve turnstile challenges due to an issue with Playwright. For more information, see [microsoft/playwright#21780](https://github.com/microsoft/playwright/issues/21780). As a temporary solution, pass the -d flag and solve the challenge manually._
> I passed it with the -d flag and it didn't lead me to a turnstile challenge but just to a click to "Verifiy you are human" type verification.

^

**Comment by Xewdy444** [comment]
Yes, I just fixed that. What I cannot fix is the inability to solve turnstile challenges.

**Comment by thofx** [comment]
on Firefox 115.0 (playwright build v1419),  the frame url return  is empty

**Comment by sean-tan** [comment]
`def _get_turnstile_frame(self) -> Optional[Frame]:
        """
        Get the Cloudflare turnstile frame.

        Returns
        -------
        Optional[Frame]
            The Cloudflare turnstile frame.
        """
        for frame in self.page.frames:
            logging.info(frame.url)
            if (
                re.match(
                    "https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/[bg]/turnstile",
                    frame.url,
                )
                is not None
            ):
                return frame

        return None`

i tried printing out the frame.url but it always loads the site im accessing and not "https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/[bg]/turnstile" regexp.

**Comment by Xewdy444** [comment]
> i keep getting [05:42:05] [ERROR] Failed to retrieve the Cloudflare clearance cookie.
> 
> `def _get_turnstile_frame(self) -> Optional[Frame]: """ Get the Cloudflare turnstile frame.
> 
> ```
>     Returns
>     -------
>     Optional[Frame]
>         The Cloudflare turnstile frame.
>     """
>     for frame in self.page.frames:
>         logging.info(frame.url)
>         if (
>             re.match(
>                 "https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/[bg]/turnstile",
>                 frame.url,
>             )
>             is not None
>         ):
>             return frame
> 
>     return None`
> ```
> 
> so i tried printing out the frame.url but it always loads the url of the site im trying to access and not the challege urls "[https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/[bg]/turnstile](https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/%5Bbg%5D/turnstile)"

https://github.com/microsoft/playwright/issues/21780
