### ISSUE TITLE
'playwright' module missing

### ISSUE THREAD

**Issue by 30Sana** [Xewdy444/CF-Clearance-Scraper#29]
from playwright._impl._api_types import Error as PlaywrightError
ModuleNotFoundError: No module named 'playwright'

Am I missing an update?

**Comment by Xewdy444** [comment]
You'll need to install playwright via `pip install playwright` and then download the browser via `python -m playwright install --with-deps firefox`

**Comment by 30Sana** [comment]
Thanks, that did the job.
