### ISSUE TITLE
Doesnt click the checkbox

### ISSUE THREAD

**Issue by DaniEnsi** [Xewdy444/CF-Clearance-Scraper#32]
The driver does not detect the checkbox, and therefore doesn't click it and fails... Also doesn't detect that it is interactive one which has to be clicked... Both on chrome driver and the other one...

**Comment by Xewdy444** [comment]
*This program currently will not be able to solve turnstile challenges due to an issue with Playwright. For more information, see https://github.com/microsoft/playwright/issues/21780. As a temporary solution, pass the `-d` flag and solve the challenge manually.*

**Comment by DaniEnsi** [comment]
When I try to use the chromedriver version, it opens, and insta closes, saying that the is no challenge present...

**Comment by DaniEnsi** [comment]
Nvm i figured out why... It shows this page when I use chromedriver:
<img width="751" alt="image" src="https://github.com/Xewdy444/CF-Clearance-Scraper/assets/74594229/35cf393f-b55c-408f-b437-9c4b620cbd40">

**Comment by Xewdy444** [comment]
The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.

**Comment by 30Sana** [comment]
> The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.

Meaning even if loaded using google chrome it wouldn't be able to solve the turnstile challenge, correct?

**Comment by Xewdy444** [comment]
> > The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.
> 
> Meaning even if loaded using google chrome it wouldn't be able to solve the turnstile challenge, correct?

If you're using undetected-chromedriver, yes.

**Comment by 30Sana** [comment]
> > > The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.
> 
> > 
> 
> > Meaning even if loaded using google chrome it wouldn't be able to solve the turnstile challenge, correct?
> 
> 
> 
> If you're using undetected-chromedriver, yes.

I'm currently using playwright but there is some challenge it's not able to solve automatically right now, would you be interested in taking a look?

**Comment by Xewdy444** [comment]
> > > > The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.
> > 
> > 
> > > 
> > 
> > 
> > > Meaning even if loaded using google chrome it wouldn't be able to solve the turnstile challenge, correct?
> > 
> > 
> > If you're using undetected-chromedriver, yes.
> 
> I'm currently using playwright but there is some challenge it's not able to solve automatically right now, would you be interested in taking a look?

Sure

**Comment by 30Sana** [comment]
> > > > > The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Meaning even if loaded using google chrome it wouldn't be able to solve the turnstile challenge, correct?
> 
> > > 
> 
> > > 
> 
> > > If you're using undetected-chromedriver, yes.
> 
> > 
> 
> > I'm currently using playwright but there is some challenge it's not able to solve automatically right now, would you be interested in taking a look?
> 
> 
> 
> Sure

Check this site out, https://flipd.gg

I run the command to parse the cookie from there but currently it's been needing a manual solve, I've been only using playwright.

**Comment by Xewdy444** [comment]
> > > > > > The instructions for installing the Selenium Wire CA certificate are in the readme. Another thing to note is that undetected-chromedriver is currently not undetected with the latest version of Chrome.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Meaning even if loaded using google chrome it wouldn't be able to solve the turnstile challenge, correct?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > If you're using undetected-chromedriver, yes.
> > 
> > 
> > > 
> > 
> > 
> > > I'm currently using playwright but there is some challenge it's not able to solve automatically right now, would you be interested in taking a look?
> > 
> > 
> > Sure
> 
> Check this site out, https://flipd.gg
> 
> I run the command to parse the cookie from there but currently it's been needing a manual solve, I've been only using playwright.

Well, unfortunately, there isn't much you can do to prevent an interactive challenge when trying to solve a managed challenge.
