### ISSUE TITLE
chromedriver keeps clicking checkbox

### ISSUE THREAD

**Issue by alexqyle** [Xewdy444/CF-Clearance-Scraper#36]
I was testing with chromedriver on commit 57c169619fd259885935beb648eeec73d7598001. I did fix `TURNSTILE_FRAME` with correct XPath to find the new iframe on site https://nowsecure.nl. When running it with `-d` option, I can see it keeps clicking the checkbox but it cannot pass the validation. I tried different versions of Chrome but no luck with that. Is there any way to successfully get the cookie by using chromedriver?

**Comment by Xewdy444** [comment]
Unfortunately, undetected-chromedriver isn't undetected with the newer versions of Chrome. The owner has stated that a full rewrite is on the way, but with no ETA. So to answer your question, there isn't a good solution at the moment.

**Comment by alexqyle** [comment]
Thanks for the reply. I will close the issue.
