### ISSUE TITLE
add proxy hold on

### ISSUE THREAD

**Issue by zhajingwen** [Xewdy444/CF-Clearance-Scraper#4]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/33952447/200165046-0be6c224-8193-4509-8d4b-65a13f53d9a6.png">
If l add proxy , it will hold on wait for this page

**Comment by Xewdy444** [comment]
Try increasing the timeout (-t <seconds>) or use a different proxy. I have just pushed a commit that increased the default timeout, so you can try using that as well.

**Comment by zhajingwen** [comment]
Yes, l have done this , have added different proxy and increasing the timeout , but they all didn't work ;
about the proxy, l use it to visit other website is normal

**Comment by Xewdy444** [comment]
![image](https://user-images.githubusercontent.com/95155966/200234397-2694f785-3fdd-41c5-97df-8a9cbe113ec6.png)
Upon testing, I was able to fetch a cf_clearance cookie consistently from this website using a proxy. I believe the issues you are experiencing are strictly network related (Slow proxy connection/Request failures).

**Comment by zhajingwen** [comment]
ok thanks , l'll have a retry
