### ISSUE TITLE
 import Error as PlaywrightError

### ISSUE THREAD

**Issue by kiennd** [Xewdy444/CF-Clearance-Scraper#42]
I got this error log:
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from playwright._impl._api_types import Error as PlaywrightError
    
I'm using python 3.8, could you tell me which version of python is recommended

**Comment by Xewdy444** [comment]
This issue is due to `playwright._impl` being made private in Playwright version 1.40.0. I have just pushed a commit that fixed this issue.
