### ISSUE TITLE
No Cloudflare challenge detected

### ISSUE THREAD

**Issue by xTobyPlayZ** [Xewdy444/CF-Clearance-Scraper#61]
Getting the message "No Cloudflare challenge detected." when using the scraper.

Command: `python3 main.py -v -f cookies.json https://www.ebgames.co.nz`

The site does have Cloudflare protection and I get a cf_clearance cookie browsing normally so not sure why this is happening.

Any help appreciated.

**Comment by Xewdy444** [comment]
Fixed in [latest commit](https://github.com/Xewdy444/CF-Clearance-Scraper/commit/630f67f784dcdaac868ceb6dc07b6bc70e4e1b97)
