### ISSUE TITLE
why can't run in docker container

### ISSUE THREAD

**Issue by zhajingwen** [Xewdy444/CF-Clearance-Scraper#9]
the docker image is the following one

mcr.microsoft.com/playwright/python

you can try it , and you will get 

```
root@c274d227588f:/home# python main.py -u https://nowsecure.nl -f cookies.json -v
[13:19:00] [INFO] Launching headless browser...
[13:19:01] [INFO] Going to https://nowsecure.nl...
[13:19:02] [INFO] Solving cloudflare challenge [JavaScript]...
[13:19:30] [ERROR] Failed to retrieve cf_clearance cookie.

```

**Comment by zhajingwen** [comment]
> the docker image is the following one
> 
> mcr.microsoft.com/playwright/python
> 
> you can try it , and you will get
> 
> ```
> root@c274d227588f:/home# python main.py -u https://nowsecure.nl -f cookies.json -v
> [13:19:00] [INFO] Launching headless browser...
> [13:19:01] [INFO] Going to https://nowsecure.nl...
> [13:19:02] [INFO] Solving cloudflare challenge [JavaScript]...
> [13:19:30] [ERROR] Failed to retrieve cf_clearance cookie.
> ```

my playwright version is `1.27.1`

**Comment by Xewdy444** [comment]
Unfortunately, I was unable to replicate this issue:
![image](https://user-images.githubusercontent.com/95155966/211428621-37a05602-bc43-4a1e-a649-862ff7827db9.png)
Did you try increasing the timeout or installing a newer version of playwright?

**Comment by zhajingwen** [comment]
> Unfortunately, I was unable to replicate this issue: ![image](https://user-images.githubusercontent.com/95155966/211428621-37a05602-bc43-4a1e-a649-862ff7827db9.png) Did you try increasing the timeout or installing a newer version of playwright?

l have try different version but it can't work ; l'll try increasing the timeout . thank you
